spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/files?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: lldragon
  resources:
    static-locations: classpath:/templates/,classpath:/static
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
    prefix: classpath:/templates/
  appliction:
    name: filesupdate

server:
  port: 8989
  servlet:
    context-path: /filesupdate

mybatis:
  mapper-locations: classpath:/com/lldragon/mapper/*.xml
  type-aliases-package: com.lldragon.entiy
